### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './activities_json'

### ISSUE THREAD

**Issue by jonathanking** [srujanpatil/nrc2strava#3]
Hi Srujan,

Thanks for making this! I am running into this problem. Do you have any idea what might be going on? Thank you!

<img width="1007" alt="Screen Shot 2020-03-22 at 9 11 51 AM" src="https://user-images.githubusercontent.com/4186997/77250266-30fd9d00-6c1d-11ea-93f7-4456eedd78cb.png">

**Comment by jonathanking** [comment]
I am using Python 3. I was able to fix this with the following changes:

1. I installed `slugify` when I should have installed `python-slugify`. I changed the `unicode(` call in that function to `str(`.
2. I manually created the `activities_json` and `activities_gpx` directories under `nrc2strava/app`.

**Comment by mrsruj** [comment]
Hey Jonathan, thanks for letting me know. I missed that in the requirements file. I'll update the changes soon.
