### ISSUE TITLE
Runs are imported as "Ride" type in strava

### ISSUE THREAD

**Issue by jonathanking** [srujanpatil/nrc2strava#4]
Hey Srujan,

Thanks again for making this. It's great! The only issue is that after being imported, my runs are labeled as Rides. Any idea how to change this default?

Thanks!

**Comment by mrsruj** [comment]
There's no direct way to do this via the API. I assume, your default workout may be set to "Ride" on Strava. You could maybe switch it to "Run" while uploading these files. I'll check if there's an indirect way to do this, else scheduling sync (if one wants to do so) would be a problem.

**Comment by jonathanking** [comment]
Ah, thanks. I forgot about that setting. My default for my profile was indeed set to Ride.

**Comment by jonathanking** [comment]
Do you think supporting heart rate is very challenging? That would be another nice feature.

**Comment by mrsruj** [comment]
> There's no direct way to do this via the API. I assume, your default workout may be set to "Ride" on Strava. You could maybe switch it to "Run" while uploading these files. I'll check if there's an indirect way to do this, else scheduling sync (if one wants to do so) would be a problem.

Hey Jonathan,
Just found a way, won't be a very neat implementation, but can do. I'll implement this soon.

**Comment by mrsruj** [comment]
> Do you think supporting heart rate is very challenging? That would be another nice feature.

I have never used HR on any of these apps so I don't know how they are structured in the JSON/GPX files. I have an idea of how Nike stores it but have no clue about Strava. It shouldn't be tough.
